# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: '铁锤子课题组'
    description: '铁锤子课题组官网，展示课题组成员、研究方向、科研成果、新闻动态与招生信息。'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: false
    show_theme_chooser: false
    logo:
      filename: "logo.png"
      text: "铁锤子课题组"

# Site footer
footer:
  copyright:
    notice: '© 2026 铁锤子课题组. All Rights Reserved.'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: "2006-01-02"
  time_format: "15:04"

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false

custom_css:
  - custom.css
